/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.16
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DistrictAdvancement : Advancement status of a team in a district.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DistrictAdvancement {
    /// Whether or not the team qualified for their District Championship
    #[serde(rename = "dcmp")]
    pub dcmp: bool,
    /// Whether or not the team qualified for the FIRST Championship
    #[serde(rename = "cmp")]
    pub cmp: bool,
}

impl DistrictAdvancement {
    /// Advancement status of a team in a district.
    pub fn new(dcmp: bool, cmp: bool) -> DistrictAdvancement {
        DistrictAdvancement {
            dcmp,
            cmp,
        }
    }
}

