/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.16
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchScoreBreakdown2025AllianceAutoReefTopRow {
    #[serde(rename = "nodeA")]
    pub node_a: bool,
    #[serde(rename = "nodeB")]
    pub node_b: bool,
    #[serde(rename = "nodeC")]
    pub node_c: bool,
    #[serde(rename = "nodeD")]
    pub node_d: bool,
    #[serde(rename = "nodeE")]
    pub node_e: bool,
    #[serde(rename = "nodeF")]
    pub node_f: bool,
    #[serde(rename = "nodeG")]
    pub node_g: bool,
    #[serde(rename = "nodeH")]
    pub node_h: bool,
    #[serde(rename = "nodeI")]
    pub node_i: bool,
    #[serde(rename = "nodeJ")]
    pub node_j: bool,
    #[serde(rename = "nodeK")]
    pub node_k: bool,
    #[serde(rename = "nodeL")]
    pub node_l: bool,
}

impl MatchScoreBreakdown2025AllianceAutoReefTopRow {
    pub fn new(node_a: bool, node_b: bool, node_c: bool, node_d: bool, node_e: bool, node_f: bool, node_g: bool, node_h: bool, node_i: bool, node_j: bool, node_k: bool, node_l: bool) -> MatchScoreBreakdown2025AllianceAutoReefTopRow {
        MatchScoreBreakdown2025AllianceAutoReefTopRow {
            node_a,
            node_b,
            node_c,
            node_d,
            node_e,
            node_f,
            node_g,
            node_h,
            node_i,
            node_j,
            node_k,
            node_l,
        }
    }
}

