---
ingress_nginx_namespace: ingress-nginx
ingress_nginx_chart_version: "{{ ingress_nginx_chart_version | default('4.12.0') }}"
ingress_http_port: "{{ ingress_http_port | default(31531) }}"
ingress_https_port: "{{ ingress_https_port | default(30556) }}"
