version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/draftAgent"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/draftTester"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/fuzzer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
