version: 2
updates:
  # Enable version updates for Cargo
  - package-ecosystem: "gomod"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
