apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fantasy-frc-app-secret
  namespace: fantasy-frc
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: fantasy-frc-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/data/fantasy-frc/app
