// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "server/model"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamStore is an autogenerated mock type for the TeamStore type
type MockTeamStore struct {
	mock.Mock
}

// CreateTeam provides a mock function with given fields: ctx, tbaId, name
func (_m *MockTeamStore) CreateTeam(ctx context.Context, tbaId string, name string) error {
	ret := _m.Called(ctx, tbaId, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tbaId, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMatchScores provides a mock function with given fields: ctx, tbaId
func (_m *MockTeamStore) GetMatchScores(ctx context.Context, tbaId string) ([]model.MatchTeamScore, error) {
	ret := _m.Called(ctx, tbaId)

	if len(ret) == 0 {
		panic("no return value specified for GetMatchScores")
	}

	var r0 []model.MatchTeamScore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.MatchTeamScore, error)); ok {
		return rf(ctx, tbaId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.MatchTeamScore); ok {
		r0 = rf(ctx, tbaId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MatchTeamScore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tbaId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetScore provides a mock function with given fields: ctx, tbaId
func (_m *MockTeamStore) GetScore(ctx context.Context, tbaId string) (map[string]int, error) {
	ret := _m.Called(ctx, tbaId)

	if len(ret) == 0 {
		panic("no return value specified for GetScore")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]int, error)); ok {
		return rf(ctx, tbaId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]int); ok {
		r0 = rf(ctx, tbaId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tbaId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeam provides a mock function with given fields: ctx, tbaId
func (_m *MockTeamStore) GetTeam(ctx context.Context, tbaId string) (*model.Team, error) {
	ret := _m.Called(ctx, tbaId)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Team, error)); ok {
		return rf(ctx, tbaId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Team); ok {
		r0 = rf(ctx, tbaId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tbaId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTeamStore creates a new instance of MockTeamStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamStore {
	mock := &MockTeamStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
