// Code generated by hand for ApiKeyStore interface.

package mocks

import (
	"context"
	"server/model"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

// MockApiKeyStore is a mock type for model.ApiKeyStore
type MockApiKeyStore struct {
	mock.Mock
}

func (_m *MockApiKeyStore) CreateApiKey(ctx context.Context, userUuid uuid.UUID, displayName string) (*model.ApiKey, string, error) {
	ret := _m.Called(ctx, userUuid, displayName)

	if len(ret) == 0 {
		panic("no return value specified for CreateApiKey")
	}

	var r0 *model.ApiKey
	var r1 string
	var r2 error

	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.ApiKey, string, error)); ok {
		return rf(ctx, userUuid, displayName)
	}

	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.ApiKey)
	}
	r1 = ret.Get(1).(string)
	r2 = ret.Error(2)

	return r0, r1, r2
}

func (_m *MockApiKeyStore) ValidateApiKey(ctx context.Context, clientId string, clientSecret string) (uuid.UUID, error) {
	ret := _m.Called(ctx, clientId, clientSecret)

	if len(ret) == 0 {
		panic("no return value specified for ValidateApiKey")
	}

	var r0 uuid.UUID
	var r1 error

	if rf, ok := ret.Get(0).(func(context.Context, string, string) (uuid.UUID, error)); ok {
		return rf(ctx, clientId, clientSecret)
	}

	r0 = ret.Get(0).(uuid.UUID)
	r1 = ret.Error(1)

	return r0, r1
}

func (_m *MockApiKeyStore) GetApiKey(ctx context.Context, id uuid.UUID) (*model.ApiKey, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetApiKey")
	}

	var r0 *model.ApiKey
	var r1 error

	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.ApiKey, error)); ok {
		return rf(ctx, id)
	}

	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.ApiKey)
	}
	r1 = ret.Error(1)

	return r0, r1
}

func (_m *MockApiKeyStore) GetApiKeysForUser(ctx context.Context, userUuid uuid.UUID) ([]model.ApiKey, error) {
	ret := _m.Called(ctx, userUuid)

	if len(ret) == 0 {
		panic("no return value specified for GetApiKeysForUser")
	}

	var r0 []model.ApiKey
	var r1 error

	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ApiKey, error)); ok {
		return rf(ctx, userUuid)
	}

	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]model.ApiKey)
	}
	r1 = ret.Error(1)

	return r0, r1
}

func (_m *MockApiKeyStore) RevokeApiKey(ctx context.Context, id uuid.UUID, userUuid uuid.UUID) error {
	ret := _m.Called(ctx, id, userUuid)

	if len(ret) == 0 {
		panic("no return value specified for RevokeApiKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, userUuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
