apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  labels:
    app: fantasy-frc
    component: migrate
spec:
  template:
    metadata:
      labels:
        app: fantasy-frc
        component: migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: fantasy-frc-migrate:latest
          command: ["postgres", "$(DATABASE_URL)", "up"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fantasy-frc-db-secret
                  key: url
