apiVersion: backstage.io/v1alpha1
kind: API

metadata:
  name: fantasy-frc
  title: Fantasy FRC API
  description: HTTP interface for the Fantasy FRC web application.
  tags:
    - go
    - openapi
    - frc
    - fantasy

spec:
  type: openapi
  lifecycle: production
  owner: user:jmisbach
  definition:
    $text: https://raw.githubusercontent.com/squirlemaster42/fantasy-frc-web/main/server/docs/openapi.yaml
