/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MatchScoreBreakdown2025Alliance struct {
	AdjustPoints int32 `json:"adjustPoints,omitempty"`
	AlgaePoints int32 `json:"algaePoints,omitempty"`
	AutoBonusAchieved bool `json:"autoBonusAchieved,omitempty"`
	AutoCoralCount int32 `json:"autoCoralCount,omitempty"`
	AutoCoralPoints int32 `json:"autoCoralPoints,omitempty"`
	AutoLineRobot1 string `json:"autoLineRobot1,omitempty"`
	AutoLineRobot2 string `json:"autoLineRobot2,omitempty"`
	AutoLineRobot3 string `json:"autoLineRobot3,omitempty"`
	AutoMobilityPoints int32 `json:"autoMobilityPoints,omitempty"`
	AutoPoints int32 `json:"autoPoints,omitempty"`
	AutoReef *MatchScoreBreakdown2025AllianceAutoReef `json:"autoReef,omitempty"`
	BargeBonusAchieved bool `json:"bargeBonusAchieved,omitempty"`
	CoopertitionCriteriaMet bool `json:"coopertitionCriteriaMet,omitempty"`
	CoralBonusAchieved bool `json:"coralBonusAchieved,omitempty"`
	EndGameBargePoints int32 `json:"endGameBargePoints,omitempty"`
	EndGameRobot1 string `json:"endGameRobot1,omitempty"`
	EndGameRobot2 string `json:"endGameRobot2,omitempty"`
	EndGameRobot3 string `json:"endGameRobot3,omitempty"`
	FoulCount int32 `json:"foulCount,omitempty"`
	FoulPoints int32 `json:"foulPoints,omitempty"`
	G206Penalty bool `json:"g206Penalty,omitempty"`
	G410Penalty bool `json:"g410Penalty,omitempty"`
	G418Penalty bool `json:"g418Penalty,omitempty"`
	G428Penalty bool `json:"g428Penalty,omitempty"`
	NetAlgaeCount int32 `json:"netAlgaeCount,omitempty"`
	Rp int32 `json:"rp,omitempty"`
	TechFoulCount int32 `json:"techFoulCount,omitempty"`
	TeleopCoralCount int32 `json:"teleopCoralCount,omitempty"`
	TeleopCoralPoints int32 `json:"teleopCoralPoints,omitempty"`
	TeleopPoints int32 `json:"teleopPoints,omitempty"`
	TeleopReef *MatchScoreBreakdown2025AllianceAutoReef `json:"teleopReef,omitempty"`
	TotalPoints int32 `json:"totalPoints,omitempty"`
	WallAlgaeCount int32 `json:"wallAlgaeCount,omitempty"`
}
