/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MatchScoreBreakdown2016Alliance struct {
	AutoPoints int32 `json:"autoPoints,omitempty"`
	TeleopPoints int32 `json:"teleopPoints,omitempty"`
	BreachPoints int32 `json:"breachPoints,omitempty"`
	FoulPoints int32 `json:"foulPoints,omitempty"`
	CapturePoints int32 `json:"capturePoints,omitempty"`
	AdjustPoints int32 `json:"adjustPoints,omitempty"`
	TotalPoints int32 `json:"totalPoints,omitempty"`
	Robot1Auto string `json:"robot1Auto,omitempty"`
	Robot2Auto string `json:"robot2Auto,omitempty"`
	Robot3Auto string `json:"robot3Auto,omitempty"`
	AutoReachPoints int32 `json:"autoReachPoints,omitempty"`
	AutoCrossingPoints int32 `json:"autoCrossingPoints,omitempty"`
	AutoBouldersLow int32 `json:"autoBouldersLow,omitempty"`
	AutoBouldersHigh int32 `json:"autoBouldersHigh,omitempty"`
	AutoBoulderPoints int32 `json:"autoBoulderPoints,omitempty"`
	TeleopCrossingPoints int32 `json:"teleopCrossingPoints,omitempty"`
	TeleopBouldersLow int32 `json:"teleopBouldersLow,omitempty"`
	TeleopBouldersHigh int32 `json:"teleopBouldersHigh,omitempty"`
	TeleopBoulderPoints int32 `json:"teleopBoulderPoints,omitempty"`
	TeleopDefensesBreached bool `json:"teleopDefensesBreached,omitempty"`
	TeleopChallengePoints int32 `json:"teleopChallengePoints,omitempty"`
	TeleopScalePoints int32 `json:"teleopScalePoints,omitempty"`
	TeleopTowerCaptured bool `json:"teleopTowerCaptured,omitempty"`
	TowerFaceA string `json:"towerFaceA,omitempty"`
	TowerFaceB string `json:"towerFaceB,omitempty"`
	TowerFaceC string `json:"towerFaceC,omitempty"`
	TowerEndStrength int32 `json:"towerEndStrength,omitempty"`
	TechFoulCount int32 `json:"techFoulCount,omitempty"`
	FoulCount int32 `json:"foulCount,omitempty"`
	Position2 string `json:"position2,omitempty"`
	Position3 string `json:"position3,omitempty"`
	Position4 string `json:"position4,omitempty"`
	Position5 string `json:"position5,omitempty"`
	Position1crossings int32 `json:"position1crossings,omitempty"`
	Position2crossings int32 `json:"position2crossings,omitempty"`
	Position3crossings int32 `json:"position3crossings,omitempty"`
	Position4crossings int32 `json:"position4crossings,omitempty"`
	Position5crossings int32 `json:"position5crossings,omitempty"`
}
