/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.12.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HubScore2026 struct {
	AutoCount int32 `json:"autoCount"`
	AutoPoints int32 `json:"autoPoints"`
	EndgameCount int32 `json:"endgameCount"`
	EndgamePoints int32 `json:"endgamePoints"`
	Shift1Count int32 `json:"shift1Count"`
	Shift1Points int32 `json:"shift1Points"`
	Shift2Count int32 `json:"shift2Count"`
	Shift2Points int32 `json:"shift2Points"`
	Shift3Count int32 `json:"shift3Count"`
	Shift3Points int32 `json:"shift3Points"`
	Shift4Count int32 `json:"shift4Count"`
	Shift4Points int32 `json:"shift4Points"`
	TeleopCount int32 `json:"teleopCount"`
	TeleopPoints int32 `json:"teleopPoints"`
	TotalCount int32 `json:"totalCount"`
	TotalPoints int32 `json:"totalPoints"`
	TransitionCount int32 `json:"transitionCount"`
	TransitionPoints int32 `json:"transitionPoints"`
}
