/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.12.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MatchScoreBreakdown2026Alliance struct {
	AdjustPoints int32 `json:"adjustPoints"`
	AutoTowerPoints int32 `json:"autoTowerPoints"`
	AutoTowerRobot1 *TowerRobot2026 `json:"autoTowerRobot1"`
	AutoTowerRobot2 *TowerRobot2026 `json:"autoTowerRobot2"`
	AutoTowerRobot3 *TowerRobot2026 `json:"autoTowerRobot3"`
	EndGameTowerPoints int32 `json:"endGameTowerPoints"`
	EndGameTowerRobot1 *TowerRobot2026 `json:"endGameTowerRobot1"`
	EndGameTowerRobot2 *TowerRobot2026 `json:"endGameTowerRobot2"`
	EndGameTowerRobot3 *TowerRobot2026 `json:"endGameTowerRobot3"`
	EnergizedAchieved bool `json:"energizedAchieved"`
	FoulPoints int32 `json:"foulPoints"`
	G206Penalty bool `json:"g206Penalty"`
	HubScore *HubScore2026 `json:"hubScore"`
	MajorFoulCount int32 `json:"majorFoulCount"`
	MinorFoulCount int32 `json:"minorFoulCount"`
	Rp int32 `json:"rp"`
	SuperchargedAchieved bool `json:"superchargedAchieved"`
	TotalAutoPoints int32 `json:"totalAutoPoints"`
	TotalPoints int32 `json:"totalPoints"`
	TotalTeleopPoints int32 `json:"totalTeleopPoints"`
	TotalTowerPoints int32 `json:"totalTowerPoints"`
	TraversalAchieved bool `json:"traversalAchieved"`
}
