/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiStatus struct {
	// Year of the current FRC season.
	CurrentSeason int32 `json:"current_season"`
	// Maximum FRC season year for valid queries.
	MaxSeason int32 `json:"max_season"`
	// True if the entire FMS API provided by FIRST is down.
	IsDatafeedDown bool `json:"is_datafeed_down"`
	// An array of strings containing event keys of any active events that are no longer updating.
	DownEvents []string `json:"down_events"`
	Ios *ApiStatusAppVersion `json:"ios"`
	Android *ApiStatusAppVersion `json:"android"`
}
