/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Rank of a team in a district.
type DistrictRanking struct {
	// TBA team key for the team.
	TeamKey string `json:"team_key"`
	// Numerical rank of the team, 1 being top rank.
	Rank int32 `json:"rank"`
	// Any points added to a team as a result of the rookie bonus.
	RookieBonus int32 `json:"rookie_bonus,omitempty"`
	// Total district points for the team.
	PointTotal int32 `json:"point_total"`
	// List of events that contributed to the point total for the team.
	EventPoints []DistrictRankingEventPoints `json:"event_points,omitempty"`
}
