/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// See the 2015 FMS API documentation for a description of each value
type MatchScoreBreakdown2015 struct {
	Blue *MatchScoreBreakdown2015Alliance `json:"blue"`
	Red *MatchScoreBreakdown2015Alliance `json:"red"`
	Coopertition string `json:"coopertition"`
	CoopertitionPoints int32 `json:"coopertition_points"`
}
