/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MatchScoreBreakdown2017Alliance struct {
	AutoPoints int32 `json:"autoPoints,omitempty"`
	TeleopPoints int32 `json:"teleopPoints,omitempty"`
	FoulPoints int32 `json:"foulPoints,omitempty"`
	AdjustPoints int32 `json:"adjustPoints,omitempty"`
	TotalPoints int32 `json:"totalPoints,omitempty"`
	Robot1Auto string `json:"robot1Auto,omitempty"`
	Robot2Auto string `json:"robot2Auto,omitempty"`
	Robot3Auto string `json:"robot3Auto,omitempty"`
	Rotor1Auto bool `json:"rotor1Auto,omitempty"`
	Rotor2Auto bool `json:"rotor2Auto,omitempty"`
	AutoFuelLow int32 `json:"autoFuelLow,omitempty"`
	AutoFuelHigh int32 `json:"autoFuelHigh,omitempty"`
	AutoMobilityPoints int32 `json:"autoMobilityPoints,omitempty"`
	AutoRotorPoints int32 `json:"autoRotorPoints,omitempty"`
	AutoFuelPoints int32 `json:"autoFuelPoints,omitempty"`
	TeleopFuelPoints int32 `json:"teleopFuelPoints,omitempty"`
	TeleopFuelLow int32 `json:"teleopFuelLow,omitempty"`
	TeleopFuelHigh int32 `json:"teleopFuelHigh,omitempty"`
	TeleopRotorPoints int32 `json:"teleopRotorPoints,omitempty"`
	KPaRankingPointAchieved bool `json:"kPaRankingPointAchieved,omitempty"`
	TeleopTakeoffPoints int32 `json:"teleopTakeoffPoints,omitempty"`
	KPaBonusPoints int32 `json:"kPaBonusPoints,omitempty"`
	RotorBonusPoints int32 `json:"rotorBonusPoints,omitempty"`
	Rotor1Engaged bool `json:"rotor1Engaged,omitempty"`
	Rotor2Engaged bool `json:"rotor2Engaged,omitempty"`
	Rotor3Engaged bool `json:"rotor3Engaged,omitempty"`
	Rotor4Engaged bool `json:"rotor4Engaged,omitempty"`
	RotorRankingPointAchieved bool `json:"rotorRankingPointAchieved,omitempty"`
	TechFoulCount int32 `json:"techFoulCount,omitempty"`
	FoulCount int32 `json:"foulCount,omitempty"`
	TouchpadNear string `json:"touchpadNear,omitempty"`
	TouchpadMiddle string `json:"touchpadMiddle,omitempty"`
	TouchpadFar string `json:"touchpadFar,omitempty"`
}
