/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Timeseries data for the 2018 game *FIRST* POWER UP. *WARNING:* This is *not* official data, and is subject to a significant possibility of error, or missing data. Do not rely on this data for any purpose. In fact, pretend we made it up. *WARNING:* This model is currently under active development and may change at any time, including in breaking ways.
type MatchTimeseries2018 struct {
	// TBA event key with the format yyyy[EVENT_CODE], where yyyy is the year, and EVENT_CODE is the event code of the event.
	EventKey string `json:"event_key,omitempty"`
	// Match ID consisting of the level, match number, and set number, eg `qm45` or `f1m1`.
	MatchId string `json:"match_id,omitempty"`
	// Current mode of play, can be `pre_match`, `auto`, `telop`, or `post_match`.
	Mode string `json:"mode,omitempty"`
	Play int32 `json:"play,omitempty"`
	// Amount of time remaining in the match, only valid during `auto` and `teleop` modes.
	TimeRemaining int32 `json:"time_remaining,omitempty"`
	// 1 if the blue alliance is credited with the AUTO QUEST, 0 if not.
	BlueAutoQuest int32 `json:"blue_auto_quest,omitempty"`
	// Number of POWER CUBES in the BOOST section of the blue alliance VAULT.
	BlueBoostCount int32 `json:"blue_boost_count,omitempty"`
	// Returns 1 if the blue alliance BOOST was played, or 0 if not played.
	BlueBoostPlayed int32 `json:"blue_boost_played,omitempty"`
	// Name of the current blue alliance POWER UP being played, or `null`.
	BlueCurrentPowerup string `json:"blue_current_powerup,omitempty"`
	// 1 if the blue alliance is credited with FACING THE BOSS, 0 if not.
	BlueFaceTheBoss int32 `json:"blue_face_the_boss,omitempty"`
	// Number of POWER CUBES in the FORCE section of the blue alliance VAULT.
	BlueForceCount int32 `json:"blue_force_count,omitempty"`
	// Returns 1 if the blue alliance FORCE was played, or 0 if not played.
	BlueForcePlayed int32 `json:"blue_force_played,omitempty"`
	// Number of POWER CUBES in the LEVITATE section of the blue alliance VAULT.
	BlueLevitateCount int32 `json:"blue_levitate_count,omitempty"`
	// Returns 1 if the blue alliance LEVITATE was played, or 0 if not played.
	BlueLevitatePlayed int32 `json:"blue_levitate_played,omitempty"`
	// Number of seconds remaining in the blue alliance POWER UP time, or 0 if none is active.
	BluePowerupTimeRemaining string `json:"blue_powerup_time_remaining,omitempty"`
	// 1 if the blue alliance owns the SCALE, 0 if not.
	BlueScaleOwned int32 `json:"blue_scale_owned,omitempty"`
	// Current score for the blue alliance.
	BlueScore int32 `json:"blue_score,omitempty"`
	// 1 if the blue alliance owns their SWITCH, 0 if not.
	BlueSwitchOwned int32 `json:"blue_switch_owned,omitempty"`
	// 1 if the red alliance is credited with the AUTO QUEST, 0 if not.
	RedAutoQuest int32 `json:"red_auto_quest,omitempty"`
	// Number of POWER CUBES in the BOOST section of the red alliance VAULT.
	RedBoostCount int32 `json:"red_boost_count,omitempty"`
	// Returns 1 if the red alliance BOOST was played, or 0 if not played.
	RedBoostPlayed int32 `json:"red_boost_played,omitempty"`
	// Name of the current red alliance POWER UP being played, or `null`.
	RedCurrentPowerup string `json:"red_current_powerup,omitempty"`
	// 1 if the red alliance is credited with FACING THE BOSS, 0 if not.
	RedFaceTheBoss int32 `json:"red_face_the_boss,omitempty"`
	// Number of POWER CUBES in the FORCE section of the red alliance VAULT.
	RedForceCount int32 `json:"red_force_count,omitempty"`
	// Returns 1 if the red alliance FORCE was played, or 0 if not played.
	RedForcePlayed int32 `json:"red_force_played,omitempty"`
	// Number of POWER CUBES in the LEVITATE section of the red alliance VAULT.
	RedLevitateCount int32 `json:"red_levitate_count,omitempty"`
	// Returns 1 if the red alliance LEVITATE was played, or 0 if not played.
	RedLevitatePlayed int32 `json:"red_levitate_played,omitempty"`
	// Number of seconds remaining in the red alliance POWER UP time, or 0 if none is active.
	RedPowerupTimeRemaining string `json:"red_powerup_time_remaining,omitempty"`
	// 1 if the red alliance owns the SCALE, 0 if not.
	RedScaleOwned int32 `json:"red_scale_owned,omitempty"`
	// Current score for the red alliance.
	RedScore int32 `json:"red_score,omitempty"`
	// 1 if the red alliance owns their SWITCH, 0 if not.
	RedSwitchOwned int32 `json:"red_switch_owned,omitempty"`
}
