/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MatchScoreBreakdown2023Alliance struct {
	ActivationBonusAchieved bool `json:"activationBonusAchieved,omitempty"`
	AdjustPoints int32 `json:"adjustPoints,omitempty"`
	AutoBridgeState string `json:"autoBridgeState,omitempty"`
	AutoChargeStationPoints int32 `json:"autoChargeStationPoints,omitempty"`
	AutoChargeStationRobot1 string `json:"autoChargeStationRobot1,omitempty"`
	AutoChargeStationRobot2 string `json:"autoChargeStationRobot2,omitempty"`
	AutoChargeStationRobot3 string `json:"autoChargeStationRobot3,omitempty"`
	AutoDocked bool `json:"autoDocked,omitempty"`
	AutoCommunity *MatchScoreBreakdown2023AllianceAutoCommunity `json:"autoCommunity,omitempty"`
	AutoGamePieceCount int32 `json:"autoGamePieceCount,omitempty"`
	AutoGamePiecePoints int32 `json:"autoGamePiecePoints,omitempty"`
	AutoMobilityPoints int32 `json:"autoMobilityPoints,omitempty"`
	MobilityRobot1 string `json:"mobilityRobot1,omitempty"`
	MobilityRobot2 string `json:"mobilityRobot2,omitempty"`
	MobilityRobot3 string `json:"mobilityRobot3,omitempty"`
	AutoPoints int32 `json:"autoPoints,omitempty"`
	CoopGamePieceCount int32 `json:"coopGamePieceCount,omitempty"`
	CoopertitionCriteriaMet bool `json:"coopertitionCriteriaMet,omitempty"`
	EndGameBridgeState string `json:"endGameBridgeState,omitempty"`
	EndGameChargeStationPoints int32 `json:"endGameChargeStationPoints,omitempty"`
	EndGameChargeStationRobot1 string `json:"endGameChargeStationRobot1,omitempty"`
	EndGameChargeStationRobot2 string `json:"endGameChargeStationRobot2,omitempty"`
	EndGameChargeStationRobot3 string `json:"endGameChargeStationRobot3,omitempty"`
	EndGameParkPoints int32 `json:"endGameParkPoints,omitempty"`
	ExtraGamePieceCount int32 `json:"extraGamePieceCount,omitempty"`
	FoulCount int32 `json:"foulCount,omitempty"`
	FoulPoints int32 `json:"foulPoints,omitempty"`
	TechFoulCount int32 `json:"techFoulCount,omitempty"`
	LinkPoints int32 `json:"linkPoints,omitempty"`
	Links []MatchScoreBreakdown2023AllianceLinks `json:"links,omitempty"`
	SustainabilityBonusAchieved bool `json:"sustainabilityBonusAchieved,omitempty"`
	TeleopCommunity *MatchScoreBreakdown2023AllianceAutoCommunity `json:"teleopCommunity,omitempty"`
	TeleopGamePieceCount int32 `json:"teleopGamePieceCount,omitempty"`
	TeleopGamePiecePoints int32 `json:"teleopGamePiecePoints,omitempty"`
	TotalChargeStationPoints int32 `json:"totalChargeStationPoints,omitempty"`
	TeleopPoints int32 `json:"teleopPoints,omitempty"`
	Rp int32 `json:"rp,omitempty"`
	TotalPoints int32 `json:"totalPoints,omitempty"`
}
