/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Webcast struct {
	// Type of webcast, typically descriptive of the streaming provider.
	Type_ string `json:"type"`
	// Type specific channel information. May be the YouTube stream, or Twitch channel name. In the case of iframe types, contains HTML to embed the stream in an HTML iframe.
	Channel string `json:"channel"`
	// The date for the webcast in `yyyy-mm-dd` format. May be null.
	Date string `json:"date,omitempty"`
	// File identification as may be required for some types. May be null.
	File string `json:"file,omitempty"`
}
