/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MatchScoreBreakdown2025AllianceAutoReefTopRow struct {
	NodeA bool `json:"nodeA"`
	NodeB bool `json:"nodeB"`
	NodeC bool `json:"nodeC"`
	NodeD bool `json:"nodeD"`
	NodeE bool `json:"nodeE"`
	NodeF bool `json:"nodeF"`
	NodeG bool `json:"nodeG"`
	NodeH bool `json:"nodeH"`
	NodeI bool `json:"nodeI"`
	NodeJ bool `json:"nodeJ"`
	NodeK bool `json:"nodeK"`
	NodeL bool `json:"nodeL"`
}
