/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Team struct {
	// TBA team key with the format `frcXXXX` with `XXXX` representing the team number.
	Key string `json:"key"`
	// Official team number issued by FIRST.
	TeamNumber int32 `json:"team_number"`
	// Team nickname provided by FIRST.
	Nickname string `json:"nickname"`
	// Official long name registered with FIRST.
	Name string `json:"name"`
	// Name of team school or affilited group registered with FIRST.
	SchoolName string `json:"school_name"`
	// City of team derived from parsing the address registered with FIRST.
	City string `json:"city"`
	// State of team derived from parsing the address registered with FIRST.
	StateProv string `json:"state_prov"`
	// Country of team derived from parsing the address registered with FIRST.
	Country string `json:"country"`
	// Will be NULL, for future development.
	Address string `json:"address"`
	// Postal code from the team address.
	PostalCode string `json:"postal_code"`
	// Will be NULL, for future development.
	GmapsPlaceId string `json:"gmaps_place_id"`
	// Will be NULL, for future development.
	GmapsUrl string `json:"gmaps_url"`
	// Will be NULL, for future development.
	Lat float64 `json:"lat"`
	// Will be NULL, for future development.
	Lng float64 `json:"lng"`
	// Will be NULL, for future development.
	LocationName string `json:"location_name"`
	// Official website associated with the team.
	Website string `json:"website,omitempty"`
	// First year the team officially competed.
	RookieYear int32 `json:"rookie_year"`
}
