/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * API version: 3.9.13
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Insights for FIRST Stronghold qualification and elimination matches.
type EventInsights2016 struct {
	// For the Low Bar - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
	LowBar []float32 `json:"LowBar"`
	// For the Cheval De Frise - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
	AChevalDeFrise []float32 `json:"A_ChevalDeFrise"`
	// For the Portcullis - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
	APortcullis []float32 `json:"A_Portcullis"`
	// For the Ramparts - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
	BRamparts []float32 `json:"B_Ramparts"`
	// For the Moat - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
	BMoat []float32 `json:"B_Moat"`
	// For the Sally Port - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
	CSallyPort []float32 `json:"C_SallyPort"`
	// For the Drawbridge - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
	CDrawbridge []float32 `json:"C_Drawbridge"`
	// For the Rough Terrain - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
	DRoughTerrain []float32 `json:"D_RoughTerrain"`
	// For the Rock Wall - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
	DRockWall []float32 `json:"D_RockWall"`
	// Average number of high goals scored.
	AverageHighGoals float32 `json:"average_high_goals"`
	// Average number of low goals scored.
	AverageLowGoals float32 `json:"average_low_goals"`
	// An array with three values, number of times breached, number of opportunities to breach, and percentage.
	Breaches []float32 `json:"breaches"`
	// An array with three values, number of times scaled, number of opportunities to scale, and percentage.
	Scales []float32 `json:"scales"`
	// An array with three values, number of times challenged, number of opportunities to challenge, and percentage.
	Challenges []float32 `json:"challenges"`
	// An array with three values, number of times captured, number of opportunities to capture, and percentage.
	Captures []float32 `json:"captures"`
	// Average winning score.
	AverageWinScore float32 `json:"average_win_score"`
	// Average margin of victory.
	AverageWinMargin float32 `json:"average_win_margin"`
	// Average total score.
	AverageScore float32 `json:"average_score"`
	// Average autonomous score.
	AverageAutoScore float32 `json:"average_auto_score"`
	// Average crossing score.
	AverageCrossingScore float32 `json:"average_crossing_score"`
	// Average boulder score.
	AverageBoulderScore float32 `json:"average_boulder_score"`
	// Average tower score.
	AverageTowerScore float32 `json:"average_tower_score"`
	// Average foul score.
	AverageFoulScore float32 `json:"average_foul_score"`
	// An array with three values, high score, match key from the match with the high score, and the name of the match.
	HighScore []string `json:"high_score"`
}
