/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.16
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EliminationAllianceStatus {
    #[serde(rename = "playoff_average", skip_serializing_if = "Option::is_none")]
    pub playoff_average: Option<f64>,
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,
    #[serde(rename = "record", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub record: Option<Option<Box<models::WltRecord>>>,
    #[serde(rename = "current_level_record", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_level_record: Option<Option<Box<models::WltRecord>>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl EliminationAllianceStatus {
    pub fn new() -> EliminationAllianceStatus {
        EliminationAllianceStatus {
            playoff_average: None,
            level: None,
            record: None,
            current_level_record: None,
            status: None,
        }
    }
}

