/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.16
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventDistrictPoints {
    /// Points gained for each team at the event. Stored as a key-value pair with the team key as the key, and an object describing the points as its value.
    #[serde(rename = "points")]
    pub points: std::collections::HashMap<String, models::EventDistrictPointsPointsValue>,
    /// Tiebreaker values for each team at the event. Stored as a key-value pair with the team key as the key, and an object describing the tiebreaker elements as its value.
    #[serde(rename = "tiebreakers", skip_serializing_if = "Option::is_none")]
    pub tiebreakers: Option<std::collections::HashMap<String, models::EventDistrictPointsTiebreakersValue>>,
}

impl EventDistrictPoints {
    pub fn new(points: std::collections::HashMap<String, models::EventDistrictPointsPointsValue>) -> EventDistrictPoints {
        EventDistrictPoints {
            points,
            tiebreakers: None,
        }
    }
}

