/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.16
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MatchScoreBreakdown2016 : See the 2016 FMS API documentation for a description of each value.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchScoreBreakdown2016 {
    #[serde(rename = "blue")]
    pub blue: Box<models::MatchScoreBreakdown2016Alliance>,
    #[serde(rename = "red")]
    pub red: Box<models::MatchScoreBreakdown2016Alliance>,
}

impl MatchScoreBreakdown2016 {
    /// See the 2016 FMS API documentation for a description of each value.
    pub fn new(blue: models::MatchScoreBreakdown2016Alliance, red: models::MatchScoreBreakdown2016Alliance) -> MatchScoreBreakdown2016 {
        MatchScoreBreakdown2016 {
            blue: Box::new(blue),
            red: Box::new(red),
        }
    }
}

