/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.16
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MatchScoreBreakdown2019 : See the 2019 FMS API documentation for a description of each value. https://frcevents2.docs.apiary.io/#/reference/match-results/score-details
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchScoreBreakdown2019 {
    #[serde(rename = "blue")]
    pub blue: Box<models::MatchScoreBreakdown2019Alliance>,
    #[serde(rename = "red")]
    pub red: Box<models::MatchScoreBreakdown2019Alliance>,
}

impl MatchScoreBreakdown2019 {
    /// See the 2019 FMS API documentation for a description of each value. https://frcevents2.docs.apiary.io/#/reference/match-results/score-details
    pub fn new(blue: models::MatchScoreBreakdown2019Alliance, red: models::MatchScoreBreakdown2019Alliance) -> MatchScoreBreakdown2019 {
        MatchScoreBreakdown2019 {
            blue: Box::new(blue),
            red: Box::new(red),
        }
    }
}

