/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.16
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchVideosInner {
    /// Can be one of 'youtube' or 'tba'
    #[serde(rename = "type")]
    pub r#type: String,
    /// Unique key representing this video
    #[serde(rename = "key")]
    pub key: String,
}

impl MatchVideosInner {
    pub fn new(r#type: String, key: String) -> MatchVideosInner {
        MatchVideosInner {
            r#type,
            key,
        }
    }
}

