/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.16
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchScoreBreakdown2023AllianceLinksInner {
    #[serde(rename = "nodes")]
    pub nodes: Vec<Nodes>,
    #[serde(rename = "row")]
    pub row: Row,
}

impl MatchScoreBreakdown2023AllianceLinksInner {
    pub fn new(nodes: Vec<Nodes>, row: Row) -> MatchScoreBreakdown2023AllianceLinksInner {
        MatchScoreBreakdown2023AllianceLinksInner {
            nodes,
            row,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Nodes {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Cone")]
    Cone,
    #[serde(rename = "Cube")]
    Cube,
}

impl Default for Nodes {
    fn default() -> Nodes {
        Self::None
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Row {
    #[serde(rename = "Bottom")]
    Bottom,
    #[serde(rename = "Mid")]
    Mid,
    #[serde(rename = "Top")]
    Top,
}

impl Default for Row {
    fn default() -> Row {
        Self::Bottom
    }
}

